# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - command: |
      nvm install 18
      nvm use 18
      npm install


# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
